# Generated by Django 5.1.3 on 2024-11-07 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='featured_portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technologies_used', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.technology')),
                ('title', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.portfolio', verbose_name='Portfolio')),
            ],
        ),
    ]
